image: node:latest

stages:
    - build
    - deploy

cache:
    paths:
        - node_modules/

build:
    image: mhart/alpine-node:12
    stage: build
    script:
        - npm install
        - npm run build

    artifacts:
        expire_in: 1 hour
        paths:
            - build
    only:
        - develop
    tags:
        - docker

deploy-to-s3:
    image: python:latest
    stage: deploy
    script:
        - pip install awscli
        - aws s3 sync build s3://scratch.slatool.com --acl public-read
    only:
        - develop
    tags:
        - docker

purge:
    image: python:latest
    stage: deploy
    script:
        - pip install awscli
        - aws cloudfront create-invalidation --distribution-id E12JNCD816RLV0 --paths "/*"
    only:
        - develop
    tags:
        - docker
